### ISSUE TITLE
Failing to parse consent string

### ISSUE THREAD

**Issue by andresilveirah** [InteractiveAdvertisingBureau/Consent-String-SDK-Swift#11]
Hello there,
I've just tried the following:
```swift
ConsentString(consentString: "BOnf5gkOnf5gkAGABBENCm-AAAAqWADABUADQAUg")
```
But the above is throwing an `ConsentStringError`. The very same consent string is parsed without a problem by the JS library ([consent-string](https://www.npmjs.com/package/consent-string)). I'm not certain if this is a bug with the Swift implementation or if the String above is, indeed, invalid. 

Any thoughts?

**Comment by andresilveirah** [comment]
Oh, I just noticed somebody's code is replacing dashes and underscores with `+` and `/` like:
```swift
let rawConsentString = "BOnf5gkOnf5gkAGABBENCm-AAAAqWADABUADQAUg"
  .replacingOccurrences(of: "-", with: "+")
  .replacingOccurrences(of: "_", with: "/")
let consentString = try ConsentString(string: rawConsentString)
```
With the code above it works. Just curious to know why the string, without replacing `-` and `_` works on JS but not on Swift.

**Comment by dkanaan** [comment]
The  dash and underscore are part of web safe base 64 while swift uses standard base 64. That’s why your code fix works.

**Comment by andresilveirah** [comment]
Thank you @dkanaan that makes a lot of sense.
