### ISSUE TITLE
Will it support TCF v2?

### ISSUE THREAD

**Issue by andresilveirah** [InteractiveAdvertisingBureau/Consent-String-SDK-Swift#12]
Hi there, 
I was going through the documentation for [TCFv2 in-app ](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#inapptcdata) and I'd like to know if the SDK will be updated to support TCF's new version.

More specifically, will it be possible to parse and get the following data? 

* General metadata
* User consent
* Legitimate interest
* Publisher restrictions
* Publisher transparency and consent
* Out-of-band (OOB) legal bases
* Specific jurisdiction disclosures
---
Extracted from the [Transparency and Consent String with Global Vendor List Format - What information is stored in a TC String?](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#what-information-is-stored-in-a-tc-string)

**Comment by andresilveirah** [comment]
@jenniferIAB is this something you could have a look at?

**Comment by chrispaterson** [comment]
@andresilveirah Jennifer no longer works for the IAB.  All that information is defined here: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#in-app-details 

FYI OOB Legal Bases apply only to "Global (shared)" TC Strings which are not possible in an in-app context because there is no way to share a cookie

**Comment by andresilveirah** [comment]
> FYI OOB Legal Bases apply only to "Global (shared)" TC Strings which are not possible in an in-app context because there is no way to share a cookie

@chrispaterson thanks for clarifying that.

I've read the [link](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#in-app-details) you posted (in fact, I've linked it in the issue as well) but I my question remain, will the iab provide a swift SDK to parse the new consent string (tcfv2 spec)?

ps. I've posted the same question on the Java SDK (not sure if you're involved in it).

**Comment by chrispaterson** [comment]
A c-based sdk is on my roadmap. Once the Java implementation is done I can focus on that

**Comment by yoalex5** [comment]
@chrispaterson, do you have any updates ?

Thanks

**Comment by QuentinBeaudouin1** [comment]
Hello, 
I don't know if you're still looking, but since i didn't find any v2 parser for iOS I made one in Objective C [here](https://github.com/Singlespot/IAB-TCF-V2-Objective-C). Guess you could use that in Swift

**Comment by beiglboe** [comment]
> A c-based sdk is on my roadmap. Once the Java implementation is done I can focus on that

@chrispaterson  Where can i find it?
