### ISSUE TITLE
Will there be a Objective-C published?

### ISSUE THREAD

**Issue by ptomasroos** [InteractiveAdvertisingBureau/Consent-String-SDK-Swift#4]
Pretty strange choice to write this in Swift.
The comparison is to write the javascript for the end user client in Web assembly or Dart.
Or to write the Android version in Kotlin, because its new and hot?

I would say that at leat 75% of the top apps out there is written in Objective-C and introducing swift into dependencies is a significant move for most publishers.

**Comment by jdowd7** [comment]
Second @ptomasroos above, objective-c sdk would be preferred.

**Comment by chrispaterson** [comment]
This is a community effort if you would like to contribute an objective-c version of the consent string I am supportive of that and will do what I can to help enable it.
