### ISSUE TITLE
When will you support consent string creation just like JS SDK

### ISSUE THREAD

**Issue by zahoork** [InteractiveAdvertisingBureau/Consent-String-SDK-Swift#5]
We the publishers(who act as CMP as well) would like to generate consent strings as well using this SDK (based on vendors list, purposes supported etc). This part seems to missing from Swift SDK, both JS SDK and even Android consent SDK added this part, so can you handle that in Swift SDK as well.  And please do update missing documentation links as well, e.g how to use this SDK.

**Comment by Pernic** [comment]
see the open Pull requests #6

**Comment by chrispaterson** [comment]
We're moving this project to TCF v2.  We have plans to create a C-based library to help with the iOS implementation of CMPs.
