### ISSUE TITLE
Need documentation

### ISSUE THREAD

**Issue by jdowd7** [InteractiveAdvertisingBureau/Consent-String-SDK-Swift#7]
Can we get an ETA on when documentation will be available for the Swift SDK?

Also can we get some clarification on the outstanding pull request, #6 , that seems to suggest that the SDK is unable to encode a consent string?

**Comment by kanstantsin-bucha** [comment]
+1 Since you force companies to get the consent from user could you please make it as easy for developers as possible?

**Comment by chrispaterson** [comment]
@truebucha who is the 'you' you are referring to?  The European Union?  This is a community effort to comply with the law, if you would like contribute to open source please do.
